apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cawspl6j0-python-gitops
  description: This is GitOps manifest for cawspl6j0-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=cawspl6j0-python
    backstage.io/kubernetes-id: cawspl6j0-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: cawspl6j0-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:cawspl6j0-python
