apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cawspl6j0-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:ca47a8a3fbcd52ee8b85a8af132ea496e1b26c04@sha256:d0e17cb29f45cb78acf70ee473654f2cfa0c16e14e7714589c6e89154835b15f
          name: container-image
