apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cawspl6j0-python
  janus-idp.io/tekton: cawspl6j0-python
  backstage.io/kubernetes-id: cawspl6j0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cawspl6j0-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
